// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ripple.Treasury.Assessment.Infrastructure;

#nullable disable

namespace Ripple.Treasury.Assessment.Infrastructure.Migrations
{
    [DbContext(typeof(TicketingDbContext))]
    [Migration("20260830011302_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ripple.Treasury.Assessment.Infrastructure.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("total_capacity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("venue");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("StartsAtUtc")
                        .HasDatabaseName("ix_events_starts_at")
                        .HasFilter("status = 'Published'");

                    b.ToTable("events", null, t =>
                        {
                            t.HasCheckConstraint("ck_events_capacity_positive", "total_capacity > 0");

                            t.HasCheckConstraint("ck_events_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_events_status", "status IN ('Draft', 'Published', 'Cancelled')");

                            t.HasCheckConstraint("ck_events_venue_not_blank", "length(btrim(venue)) > 0");
                        });
                });

            modelBuilder.Entity("Ripple.Treasury.Assessment.Infrastructure.Entities.PricingTier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Allocation")
                        .HasColumnType("integer")
                        .HasColumnName("allocation");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("PriceAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("price_amount");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("price_currency");

                    b.HasKey("Id")
                        .HasName("pk_pricing_tiers");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_pricing_tiers_event");

                    b.HasIndex("EventId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_pricing_tiers_event_name");

                    b.ToTable("pricing_tiers", null, t =>
                        {
                            t.HasCheckConstraint("ck_pricing_tiers_allocation_positive", "allocation > 0");

                            t.HasCheckConstraint("ck_pricing_tiers_currency_iso", "price_currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_pricing_tiers_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_pricing_tiers_price_non_negative", "price_amount >= 0");
                        });
                });

            modelBuilder.Entity("Ripple.Treasury.Assessment.Infrastructure.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("PurchaserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("purchaser_email");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("request_fingerprint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Completed")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_purchases");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_purchases_created");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_purchases_event");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_purchases_idempotency_key");

                    b.ToTable("purchases", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchases_currency_iso", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_purchases_email_shape", "purchaser_email ~ '^[^@[:space:]]+@[^@[:space:]]+\\.[^@[:space:]]+$'");

                            t.HasCheckConstraint("ck_purchases_status", "status IN ('Completed', 'Cancelled')");

                            t.HasCheckConstraint("ck_purchases_total_non_negative", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("Ripple.Treasury.Assessment.Infrastructure.Entities.PurchaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ItemTotal")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("item_total");

                    b.Property<Guid>("PricingTierId")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_tier_id");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_purchase_items");

                    b.HasIndex("PricingTierId")
                        .HasDatabaseName("ix_purchase_items_tier");

                    b.HasIndex("PurchaseId")
                        .HasDatabaseName("ix_purchase_items_purchase");

                    b.HasIndex("PurchaseId", "PricingTierId")
                        .IsUnique()
                        .HasDatabaseName("uq_purchase_items_purchase_tier");

                    b.ToTable("purchase_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchase_items_price_non_negative", "unit_price >= 0");

                            t.HasCheckConstraint("ck_purchase_items_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_purchase_items_total_consistent", "item_total = unit_price * quantity");
                        });
                });

            modelBuilder.Entity("Ripple.Treasury.Assessment.Infrastructure.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("PricingTierId")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_tier_id");

                    b.Property<Guid?>("PurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_id");

                    b.Property<int>("SeatOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("seat_ordinal");

                    b.Property<DateTimeOffset?>("SoldAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sold_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Available")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("PurchaseId")
                        .HasDatabaseName("ix_tickets_purchase")
                        .HasFilter("purchase_id IS NOT NULL");

                    b.HasIndex("EventId", "PricingTierId")
                        .HasDatabaseName("ix_tickets_event_tier");

                    b.HasIndex(new[] { "PricingTierId", "SeatOrdinal" }, "ix_tickets_available")
                        .HasDatabaseName("ix_tickets_available")
                        .HasFilter("status = 'Available'");

                    b.HasIndex(new[] { "PricingTierId", "SeatOrdinal" }, "uq_tickets_tier_ordinal")
                        .IsUnique()
                        .HasDatabaseName("uq_tickets_tier_ordinal");

                    b.ToTable("tickets", null, t =>
                        {
                            t.HasCheckConstraint("ck_tickets_sold_has_purchase", "(status = 'Available' AND purchase_id IS NULL     AND sold_at IS NULL)\nOR (status = 'Sold'      AND purchase_id IS NOT NULL AND sold_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_tickets_status", "status IN ('Available', 'Sold')");
                        });
                });

            modelBuilder.Entity("Ripple.Treasury.Assessment.Infrastructure.Entities.PricingTier", b =>
                {
                    b.HasOne("Ripple.Treasury.Assessment.Infrastructure.Entities.Event", "Event")
                        .WithMany("Tiers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pricing_tiers_events_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Ripple.Treasury.Assessment.Infrastructure.Entities.Purchase", b =>
                {
                    b.HasOne("Ripple.Treasury.Assessment.Infrastructure.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchases_events_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Ripple.Treasury.Assessment.Infrastructure.Entities.PurchaseItem", b =>
                {
                    b.HasOne("Ripple.Treasury.Assessment.Infrastructure.Entities.PricingTier", "PricingTier")
                        .WithMany()
                        .HasForeignKey("PricingTierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_items_pricing_tiers_pricing_tier_id");

                    b.HasOne("Ripple.Treasury.Assessment.Infrastructure.Entities.Purchase", "Purchase")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_items_purchases_purchase_id");

                    b.Navigation("PricingTier");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Ripple.Treasury.Assessment.Infrastructure.Entities.Ticket", b =>
                {
                    b.HasOne("Ripple.Treasury.Assessment.Infrastructure.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_events_event_id");

                    b.HasOne("Ripple.Treasury.Assessment.Infrastructure.Entities.PricingTier", "PricingTier")
                        .WithMany()
                        .HasForeignKey("PricingTierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_pricing_tiers_pricing_tier_id");

                    b.HasOne("Ripple.Treasury.Assessment.Infrastructure.Entities.Purchase", "Purchase")
                        .WithMany()
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_purchases_purchase_id");

                    b.Navigation("Event");

                    b.Navigation("PricingTier");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Ripple.Treasury.Assessment.Infrastructure.Entities.Event", b =>
                {
                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("Ripple.Treasury.Assessment.Infrastructure.Entities.Purchase", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
